title: Surfing The Keybord ⌨⌨⌨
subtitle: 這是一個紀錄問題解決過程或想法的部落格，可能很雜亂，可能有錯誤，但也有可能是你我都曾遇到的問題
keywords: 'C#,MSSQL,DotNet,DotNetMVC,Javascript,jQuery,EntityFramework'
url: https://charley85470.github.io/
author: Charley
language: zh-TW
timezone: Asia/Taipei

deploy:
  type: git
  repo: https://github.com/charley85470/charley85470.github.io
  branch: github-page-blog

pretty_urls:
  trailing_index: false # 設置 false 則會永遠移除 index.html
  trailing_html: false # 設置 false 則會永遠移除 html
